# Generated by Django 2.2.16 on 2022-11-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
