# Generated by Django 3.0 on 2022-11-23 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20221124_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='rewiew',
            new_name='review',
        ),
    ]
